/**********************************************************************

	--- Dlgedit generated file ---

	File: editGroupData.h
	Last generated: Tue Nov 25 21:52:35 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef editGroupData_included
#define editGroupData_included

#include <qdialog.h>
#include <qlistbox.h>
#include <qpushbt.h>

class editGroupData : public QDialog
{
    Q_OBJECT

public:

    editGroupData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~editGroupData();

public slots:


protected slots:

    virtual void del();
    virtual void add();
    virtual void ok();
    virtual void cancel();

protected:
    QListBox* m_Users;
    QListBox* m_Group;
    QPushButton* pbadd;
    QPushButton* pbdel;
    QPushButton* pbok;
    QPushButton* pbcancel;

};

#endif // editGroupData_included
