/**********************************************************************

	--- Dlgedit generated file ---

	File: editGroupData.cpp
	Last generated: Sat Nov 29 12:48:35 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#include "globals.h"
#include "misc.h"
#include "editGroupData.h"

#define Inherited QDialog

#include <qlabel.h>

editGroupData::editGroupData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE )
{
	m_Users = new QListBox( this, "m_Users" );
	m_Users->setGeometry( 10, 30, 200, 130 );
	m_Users->setFrameStyle( 51 );
	m_Users->setLineWidth( 2 );

	QLabel* tmpQLabel;
	tmpQLabel = new QLabel( this, "Label_1" );
	tmpQLabel->setGeometry( 20, 10, 100, 20 );
	tmpQLabel->setText(i18n("Users"));
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	m_Group = new QListBox( this, "m_Group" );
	m_Group->setGeometry( 290, 30, 200, 130 );
	m_Group->setFrameStyle( 51 );
	m_Group->setLineWidth( 2 );

	pbadd = new QPushButton( this, "pbadd" );
	pbadd->setGeometry( 230, 50, 40, 30 );
	connect( pbadd, SIGNAL(clicked()), SLOT(add()) );
	pbadd->setText( "->" );
	pbadd->setAutoRepeat( FALSE );
	pbadd->setAutoResize( FALSE );

	pbdel = new QPushButton( this, "pbdel" );
	pbdel->setGeometry( 230, 100, 40, 30 );
	connect( pbdel, SIGNAL(clicked()), SLOT(del()) );
	pbdel->setText( "<-" );
	pbdel->setAutoRepeat( FALSE );
	pbdel->setAutoResize( FALSE );

	pbok = new QPushButton( this, "PushButton_3" );
	pbok->setGeometry( 70, 190, 100, 30 );
	connect( pbok, SIGNAL(clicked()), SLOT(ok()) );
	pbok->setText(i18n("OK"));
	pbok->setAutoRepeat( FALSE );
	pbok->setAutoResize( FALSE );

	pbcancel = new QPushButton( this, "pbcancel" );
	pbcancel->setGeometry( 200, 190, 100, 30 );
	connect( pbcancel, SIGNAL(clicked()), SLOT(cancel()) );
	pbcancel->setText(i18n("Cancel"));
	pbcancel->setAutoRepeat( FALSE );
	pbcancel->setAutoResize( FALSE );

	tmpQLabel = new QLabel( this, "Label_2" );
	tmpQLabel->setGeometry( 300, 10, 100, 20 );
	tmpQLabel->setText(i18n("Groups"));
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	resize( 500, 250 );
}


editGroupData::~editGroupData()
{
}
void editGroupData::add()
{
}
void editGroupData::del()
{
}
void editGroupData::ok()
{
}
void editGroupData::cancel()
{
}
