#define KU_HOMEDIR_PERM ${KU_HOMEDIR_PERM}
#define KU_MAILBOX_PERM ${KU_MAILBOX_PERM}
#define KU_MAILBOX_GID ${KU_MAILBOX_GID}

#define KU_HOMETEMPLATE "${KU_HOMETEMPLATE}"
#define KU_FIRSTUID ${KU_FIRSTUID}
#define KU_FIRSTGID ${KU_FIRSTGID}
#define KU_USERPRIVATEGROUP ${KU_USERPRIVATEGROUP}

#cmakedefine HAVE_SHADOW_H
#cmakedefine HAVE_CRYPT_H
#cmakedefine HAVE_FGETSPENT
#cmakedefine HAVE_FGETPWENT
#cmakedefine HAVE_FGETGRENT
