/**********************************************************************

	--- Qt Architect generated file ---

	File: userDefaultsPageData.h
	Last generated: Mon Oct 12 00:56:45 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef userDefaultsPageData_included
#define userDefaultsPageData_included

#include <qwidget.h>
#include <qchkbox.h>
#include <qlined.h>
#include <qcombo.h>

class userDefaultsPageData : public QWidget
{
    Q_OBJECT

public:

    userDefaultsPageData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~userDefaultsPageData();

public slots:


protected slots:


protected:
    QComboBox* shell;
    QLineEdit* home;
    QCheckBox* createHomeDir;
    QCheckBox* copySkel;

};

#endif // userDefaultsPageData_included
